route:
    receiver: 'email_receiver'

receivers:
    - name: 'email_receiver'
      email_configs:
          - send_resolved: true
            to: alerts@mobeigi.com
            from: Observability <obs@mobeigi.com>
            smarthost: email-smtp.ap-southeast-2.amazonaws.com:587
            auth_username: username
            auth_password: password
