global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    metrics_path: /pushgateway/metrics
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'atom-nodeexporter'
    scrape_interval: 30s
    scheme: https
    basic_auth:
        username: 'admin'
        password_file: /etc/prometheus/.secrets/atom.mobeigi.com.htpasswd
    metrics_path: /node_exporter/metrics
    static_configs:
      - targets: ['mobeigi.com']
      
  - job_name: 'nginx'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginxexporter:9113']

alerting:
  alertmanagers:
  - scheme: http
    path_prefix: /alertmanager
    static_configs:
    - targets: 
      - 'alertmanager:9093'

